# Generated by Django 2.2.6 on 2019-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_remove_allfieldstypes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfieldstypes',
            name='intg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
