# Generated by Django 2.2.6 on 2019-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_allfieldstypes_intg'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfieldstypes',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
