# Generated by Django 2.2.6 on 2019-10-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_allfieldstypes_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfieldstypes',
            name='null_bul',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='allfieldstypes',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
