# Generated by Django 2.2.6 on 2019-10-31 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_auto_20191031_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfieldstypes',
            name='pos_int',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allfieldstypes',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
