# Generated by Django 2.2.6 on 2019-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_auto_20191031_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfieldstypes',
            name='pos_smal_int',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allfieldstypes',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
