# Generated by Django 2.2.6 on 2019-10-31 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0007_auto_20191031_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allfieldstypes',
            old_name='ip',
            new_name='IP',
        ),
        migrations.RemoveField(
            model_name='allfieldstypes',
            name='id',
        ),
        migrations.AddField(
            model_name='allfieldstypes',
            name='URL',
            field=models.URLField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='allfieldstypes',
            name='text',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='allfieldstypes',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='allfieldstypes',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
