# Generated by Django 2.2.6 on 2019-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0008_auto_20191031_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfieldstypes',
            name='image',
            field=models.ImageField(max_length=40, null=True, upload_to=None),
        ),
    ]
